### ISSUE TITLE
Base layout for actions

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#15]
For our base layout, we'll have:

1. user settings as a partially visible, non-collapsible action
2. full screen mode as a partially visible and collapsible action
3. table of contents as a partially visible and collapsible action
4. the overflow menu as an always visible, non-collapsible action
5. jump to position as an action that's strictly displayed in the overflow menu

When actions are collapsed in the overflow menu, they retain their order. This means that on a smaller screen, our base layout will have:

- user settings
- overflow menu:
  - full screen
  - table of contents
  - jump to position

We'll also use this base layout to further test how focus and screen reader support is handled over a full implementation of actions.

**Comment by JayPanoz** [comment]
Since we’re trying to cover edge cases while implementing this base layout, let’s list the ones we encountered or are aware of. 

- No shortcut to display for overflow menu items → shortcut is simply not displayed.
- no action to display in overflow → currently the overflow menu action icon is not displayed but what happens when in immersive move w/o menu and nothing visible to hint at the existence of actions icons? 
- no fullscreen if not supported → check is using `document.fullscreenEnabled` at the moment, which doesn’t work with iPadOS – it technically supports fullscreen, albeit very opinionatedly, with a close button always displayed and keyboard disabled for security reasons so  not sure it’s worth adding support for it at the moment.
- lack of a proper Table of Contents? Do we display the action with some fallback text telling there is nothing to display in the modal, or not display the action at all?

**Comment by HadrienGardeur** [comment]
> lack of a proper Table of Contents? Do we display the action with some fallback text telling there is nothing to display in the modal, or not display the action at all?

Given the importance of a table of contents for accessibility, I'm in favor of always displaying an action for it. An empty state could cover the case where this is empty.

**Comment by JayPanoz** [comment]
> Given the importance of a table of contents for accessibility, I'm in favor of always displaying an action for it. An empty state could cover the case where this is empty.

Alright that was implemented in the Actions branch, although not testable on deploy as there is a Table of Contents for both books. The string can be customised in Resources. At the moment it checks for the length of `Links.items` but can be refined in the future, as we’ll probably learn what looks like a short Table of Contents may not provide useful information.

<img width="324" alt="ToC Modal open with Message: The table of contents was not provided for this publication" src="https://github.com/user-attachments/assets/576f68b6-3935-44a4-889f-ff688e70bab4">

> no action to display in overflow → currently the overflow menu action icon is not displayed but what happens when in immersive move w/o menu and nothing visible to hint at the existence of actions icons?

That was modified as well, with the button always displayed, even when there is nothing to put into it. Different tooltips in that case. 

When the action is active as a menu and contains overflow actions: 

<img width="180" alt="Tooltip displays More Actions" src="https://github.com/user-attachments/assets/aaeafae8-786e-4990-8d7e-f8e0ba9201f4">

When the action is a hint and contains nothing:

<img width="186" alt="Tooltip displays Toggle Actions" src="https://github.com/user-attachments/assets/3a5a2ad8-0078-44f6-92c2-cef9aecb1add">

When being a hint, the button toggles immersive mode instead of displaying a menu, which should help on mobile at first-sight since there is no way to hover the top bar. 

This is not testable on deploy as-is but I can temporarily disable the “Jump to Position” Action, that is set to `overflow`, so that it’s testable if you wish.
