### ISSUE TITLE
Support for paginated content using auto columns/spreads and core affordances

### ISSUE THREAD

**Issue by HadrienGardeur** [edrlab/thorium-web#2]
For this task, we're targeting an auto column/spread mode.

For reflowable EPUB files, this means:

- [x] supporting a break point where we only display a single column, without "padding" around the content area
- [x] past that break point, we'll display as many columns as we can fit with a reasonable line length

For FXL files, this means:

- [x] defaulting to a single page spread for anything smaller in width than an iPad in landscape mode
- [x] displaying a two page spread for anything larger than that
- [ ] but supporting the following properties as well:
  - [ ] `"page": "center"` to force a single centered page
  - [ ] `"meaningfulSpread": true` or `"spread": "both"` in the `readingOrder` to force the display of a full spread

Core affordances for paginated content include:

- [x] buttons for moving forward/backward in the progression of the publication
- [x] arrow keys and space bar
- [x] taps
- [x] swipes
- [x] pinch zoom on FXL

Since this is the very core of what an ebook reader does, we'll spend as much time/efforts as needed to get all of this feeling just right.

**Comment by JayPanoz** [comment]
Note: for FXL files EPUBNavigator already has an auto-mode implemented so it’s tricky to override it AS-IS in the absence of a Preference API, especially as it directly handles resizing and orientation change to scale pages and switch from a single one to a spread – so there’s quite a lot of room for bugs, side effects, unsynchronised states or data, etc.

This is why this is unaddressed/unchecked at the moment. Not sure whether it should move to another issue so that we can close this one, or stay here with the issue being kept open until we come back to it.

**Comment by HadrienGardeur** [comment]
I'm moving this one in review.

For `page: center` and meaningful spreads, we'll open separate issues in the `ts-toolkit` and track them with our own issues here.
